spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 3128970483@qq.com
    password: womfuejfqzzqdecc
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  security:
    filter:
      order: -100
    jwt:
      key: abcdefghijklmnopqrstuvwxyz1234567890
      expire: 7
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  minio:
    endpoint: 'http://localhost:9000'
    username: 'minioadmin'
    password: 'minioadmin'